config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'
  get 'about', to: 'public/homes#about'
  get 'customers/my_page', to: 'public/customers#show'
  get 'customers/edit', to: 'public/customers#edit'
  get 'customers/unsubscribe', to: 'public/customers#unsubscribe'
  get 'admin', to: 'admin/homes#top'
  post 'customers', to: 'public/customers#update'

  # 管理者用 ## URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show]
  end

  # 顧客用  ## URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  namespace :public do
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  # enum の定義
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
     @customer = Customer.find(params[:id])
     @customer.update(customer_params)
     # とりあえず以下の分岐は後で。
     redirect_to edit_admin_customer_path(@customer)
  end

  private
  # ストロングパラメータ
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @admin_side_orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path(@item.id)
  end

  def index
    @items  = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    # show画面でもよいのか？？
    redirect_to admin_items_path(@item)
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image) #image忘れず
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
     super
  end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

  protected
  ## deviseのメソッド
  def after_sign_in_path_for(resource)
    admin_path  # 管理者topの注文履歴一覧画面
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h4>さんの会員情報詳細</h4>

<%= form_with model: @customer, local:true do |f| %>

<h6>会員ID</h6> <%# ここにオブジェクト.id みたいなもの%>
<h6>氏名</h6>
<%= f.text_field :last_name %><%= f.text_field :first_name %>
<h6>フリガナ</h6>
<%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %>
<h6>郵便番号</h6>
<%= f.number_field :postal_code %>
<h6>住所</h6>
<%= f.text_field :address %>
<h6>電話番号</h6>
<%= f.telephone_field :phone %>
<h6>メールアドレス</h6>
<%= f.email_field :email %>

<h6>会員ステータス</h6>
<!--以下、後で調べるor聞く-->
<!--%= f.radio_button :status, :male %>-->
<!--%= f.label :status, "有効" %>-->
<!--%= f.radio_button :status, :female %>-->
<!--%= f.label :status, "退会" %>-->

<h4><%= f.submit "変更を保存" %></h4>
<% end %>

app/views/admin/customers/index.html.erb
<h4>会員一覧</h4>
  <table class="table">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.last_name %><%= customer.first_name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.is_deleted %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

app/views/admin/customers/show.html.erb
<h4>さんの会員詳細</h4>
<h6>会員ID</h6>
<h6>氏名</h6>
<h6>フリガナ</h6>
<h6>郵便番号</h6>
<h6>住所</h6>
<h6>電話番号</h6>
<h6>メールアドレス</h6>
<h6>会員ステータス</h6>
<%= link_to "編集する", edit_admin_customer_path(@customer) %>
<%= link_to "注文履歴一覧を見る", admin_path %>

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>
<%= form_with model: @item, local:true do |f| %>
  <h4>商品画像</h4>
    <%= f.file_field :image, accept: "image/*" %>
  <h4>商品名</h4><%= f.text_field :name %>
  <h4>商品説明</h4><%= f.text_area :introduction %>
  <h4>税抜価格</h4><%= f.number_field :price %> 円
  <h2>
    <%= f.submit '税抜価格' %>
  </h2>
<% end %>

app/views/admin/items/index.html.erb
<h4>商品一覧</h4>
  <table class="table">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

app/views/admin/items/new.html.erb
<h2>商品新規登録</h2>
<%= form_with model: @item, url: new_admin_item_path, local:true do |f| %>

  <h4>商品画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>商品名</h4>
  <%= f.text_field :name %>
  <h4>商品説明</h4>
  <%= f.text_area :introduction %>
  <h4>税抜価格</h4>
  <%= f.number_field :price %> 円

  <h2>
  <%= f.submit '新規登録' %>
  </h2>
<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>
  <!--単に画像表示-->
  <h4>商品名</h4>
  <h4>商品説明</h4>
  <h4>税込価格(税抜価格)</h4>

app/views/admin/orders/show.html.erb
<h2>注文履歴詳細</h2>

<h4>購入者</h4>
<h4>注文日</h4>
<h4>配送先</h4>
<h4>支払い方法</h4>
<h4>購入者</h4>


<table class="table">
  <thead>
    <tr>
      <th>商品名</th>
      <th>単価(税込)</th>
      <th>数量</th>
      <th>小計</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <!--<tbody>-->
  <!-- 以下の@ordersはURL指定できるのか？それともhomesコントローラの@ordersを指定するには？ -->
  <!-- @orders は 会員側でも使いそうなので、@admin_side_orderとしておけば、1つだけ場所も特定できる。-->
  <!--大なり% admin_side_orders.each do |item| %>-->
    <!--<tr>-->
      <!--<td>大なり%= item.id %></td>-->
      <!--<td>大なり%= item.name %></td>-->
      <!--<td>大なり%= item.price %></td>-->
    <!--</tr>-->
  <!--大なり% end %>-->
  </tbody>
</table>